#include "elements.h"

#define LINE   118
#define COLUMN   3

// Símbolo / Elemento / N. Atômico
char *elementsTable[LINE][COLUMN] = {
"H ", "Hidrogênio"	, "1",
"He", "Hélio"		, "2",
"Li", "Lítio"		, "3",
"Be", "Berílio"		, "4",
"B ", "Boro"		, "5",
"C ", "Carbono"		, "6",
"N ", "Nitrogênio"	, "7",
"O ", "Oxigênio"	, "8",
"F ", "Flúor"		, "9",
"Ne", "Neônio"		, "10",
"Na", "Sódio"		, "11",
"Mg", "Magnésio"	, "12",
"Al", "Alumínio"	, "13",
"Si", "Silício"		, "14",
"P ", "Fósforo"		, "15",
"S ", "Enxofre"		, "16",
"Cl", "Cloro"		, "17",
"Ar", "Argônio"		, "18",
"K ", "Potássio"	, "19",
"Ca", "Cálcio"		, "20",
"Sc", "Escândio"	, "21",
"Ti", "Titânio"		, "22",
"V ", "Vanádio"		, "23",
"Cr", "Cromo"		, "24",
"Mn", "Manganês"	, "25",
"Fe", "Ferro"		, "26",
"Co", "Cobalto"		, "27",
"Ni", "Níquel"		, "28",
"Cu", "Cobre"		, "29",
"Zn", "Zinco"		, "30",
"Ga", "Gálio"		, "31",
"Ge", "Germânio"	, "32",
"As", "Arsénio"		, "33",
"Se", "Selénio"		, "34",
"Br", "Bromo"		, "35",
"Kr", "Criptônio"	, "36",
"Rb", "Rubídio"		, "37",
"Sr", "Estrôncio"	, "38",
"Y ", "Ítrio"		, "39",
"Zr", "Zircônio"	, "40",
"Nb", "Nióbio"		, "41",
"Mo", "Molibdénio"	, "42",
"Tc", "Tecnécio"	, "43",
"Ru", "Rutênio"		, "44",
"Rh", "Ródio"		, "45",
"Pd", "Paládio"		, "46",
"Ag", "Prata"		, "47",
"Cd", "Cádmio"		, "48",
"In", "Índio"		, "49",
"Sn", "Estanho"		, "50",
"Sb", "Antimônio"	, "51",
"Te", "Telúrio"		, "52",
"I ", "Iodo"		, "53",
"Xe", "Xenônio"		, "54",
"Cs", "Césio"		, "55",
"Ba", "Bário"		, "56",
"La", "Lantânio"	, "57",
"Ce", "Cério"		, "58",
"Pr", "Praseodímio"	, "59",
"Nd", "Neodímio"	, "60",
"Pm", "Promécio"	, "61",
"Sm", "Samário"		, "62",
"Eu", "Európio"		, "63",
"Gd", "Gadolínio"	, "64",
"Tb", "Térbio"		, "65",
"Dy", "Disprósio"	, "66",
"Ho", "Hólmio"		, "67",
"Er", "Érbio"		, "68",
"Tm", "Túlio"		, "69",
"Yb", "Itérbio"		, "70",
"Lu", "Lutécio"		, "71",
"Hf", "Háfnio"		, "72",
"Ta", "Tântalo"		, "73",
"W ", "Tungstênio"	, "74",
"Re", "Rênio"		, "75",
"Os", "Ósmio"		, "76",
"Ir", "Japônio"		, "77",
"Pt", "Platina"		, "78",
"Au", "Ouro"		, "79",
"Hg", "Mercúrio"	, "80",
"Tl", "Tálio"		, "81",
"Pb", "Chumbo"		, "82",
"Bi", "Bismuto"		, "83",
"Po", "Polônio"		, "84",
"At", "Ástato"		, "85",
"Rn", "Rádon"		, "86",
"Fr", "Frâncio"		, "87",
"Ra", "Rádio"		, "88",
"Ac", "Actínio"		, "89",
"Th", "Tório"		, "90",
"Pa", "Protactínio"	, "91",
"U" , "Urânio"		, "92",
"Np", "Ne(p)túnio"	, "93",
"Pu", "Plutônio"	, "94",
"Am", "Amerício"	, "95",
"Cm", "Cúrio"		, "96",
"Bk", "Berquélio"	, "97",
"Cf", "Califórnio"	, "98",
"Es", "Einsténio"	, "99",
"Fm", "Férmio"		, "100",
"Md", "Mendelévio"	, "101",
"No", "Nobélio"		, "102",
"Lr", "Laurêncio"	, "103",
"Rf", "Rutherfórdio", "104",	
"Db", "Dúbnio"		, "105",
"Sg", "Seabórgio"	, "106",
"Bh", "Bóhrio"		, "107",
"Hs", "Hássio"		, "108",
"Mt", "Meitnério"	, "109",
"Ds", "Darmstácio"	, "110",
"Rg", "Roentgénio"	, "111",
"Cn", "Copernício"	, "112",
"Nh", "Nipônio"		, "113",
"Fl", "Fleróvio"	, "114",
"Mc", "Moscóvio"	, "115",
"Lv", "Livermório"	, "116",
"Ts", "Tenesso"		, "117",
"Og", "Oganésson"	, "118"};

void qmc::_elementsUsage() {
	using namespace std;
	std::cout << "" << std::endl;
	for(int l=0; l<LINE; l++) {
		// Line x Column:
		cout << std::left;
		cout << std::setw(2)  << elementsTable[l][0];
		cout << " - ";
		cout << std::setw(12) << elementsTable[l][1];
		cout << " - ";
		cout << elementsTable[l][2] << endl;
	}
}