#pragma once
#include <wx/frame.h>
#include <wx/filepicker.h>
#include <wx/textctrl.h>

#include <wx/panel.h>
#include <wx/stattext.h>
#include <wx/sizer.h>
#include "IDs.h"

class FrameFilePicker : public wxFrame {
	wxTextCtrl* m_textCtrl;
    void OnPathChanged(wxFileDirPickerEvent& evt);

public:
    FrameFilePicker(const wxString& title);

private:
    wxDECLARE_EVENT_TABLE();
};

// Add the event handler to the event table. As you can see we use the
// window ID to link the event handler to the wxFilePickerCtrl we created.
wxBEGIN_EVENT_TABLE(FrameFilePicker, wxFrame)
    EVT_FILEPICKER_CHANGED(FilePickerID, FrameFilePicker::OnPathChanged)
wxEND_EVENT_TABLE()
//*********************************************************
FrameFilePicker::FrameFilePicker(const wxString& title)
    : wxFrame(NULL, wxID_ANY, title), m_textCtrl(0)
{
    // Create a top-level panel to hold all the contents of the frame
    wxPanel* panel = new wxPanel(this, wxID_ANY);

    // Create a wxFilePickerCtrl control
    wxFilePickerCtrl* filePickerCtrl = new wxFilePickerCtrl(panel, FilePickerID,
        wxEmptyString, wxFileSelectorPromptStr, wxFileSelectorDefaultWildcardStr,
        wxDefaultPosition, wxSize(350, wxDefaultCoord));

    // We add a wxTextCtrl that will contain the same path as
    // the wxFilePickerCtrl. This is done by using the event
    // generated by the wxFilePickerCtrl when the path changes.
    wxStaticText* staticText = new wxStaticText(panel, wxID_ANY, "Selected Path:");
    m_textCtrl = new wxTextCtrl(panel, wxID_ANY);

    // Set up the sizer for the panel
    wxBoxSizer* panelSizer = new wxBoxSizer(wxVERTICAL);
    panelSizer->Add(filePickerCtrl, 0, wxEXPAND | wxALL, 5);
    panelSizer->AddSpacer(15);
    panelSizer->Add(staticText, 0, wxEXPAND | wxLEFT, 5);
    panelSizer->Add(m_textCtrl, 0, wxEXPAND | wxALL, 5);
    panel->SetSizer(panelSizer);

    // Set up the sizer for the frame and resize the frame
    // according to its contents
    wxBoxSizer* topSizer = new wxBoxSizer(wxHORIZONTAL);
    topSizer->Add(panel, 1, wxEXPAND);
    SetSizerAndFit(topSizer);
}

// This event handler will be called when the path
// of the wxFilePickerCtrl has changed
void FrameFilePicker::OnPathChanged(wxFileDirPickerEvent& evt) {
	int i = evt.GetId();
    if (m_textCtrl)
        m_textCtrl->SetValue(evt.GetPath());
		//m_textCtrl->SetValue(s);
}