#pragma once
#include <wx/frame.h>
#include <wx/filepicker.h>
#include <wx/textctrl.h>

#include <wx/panel.h>
#include <wx/stattext.h>
#include <wx/sizer.h>
#include "IDs.h"

class Picker : public wxFrame {
	wxTextCtrl* m_textCtrl;
	wxTextCtrl* m_textCtrl2;
	//wxTextCtrl* m_textCtrl2;
    void OnPathChanged(wxFileDirPickerEvent& evt);

public:
    Picker(const wxString& title);

private:
    wxDECLARE_EVENT_TABLE();
};

// Add the event handler to the event table. As you can see we use the
// window ID to link the event handler to the wxDirPickerCtrl we created.
wxBEGIN_EVENT_TABLE(Picker, wxFrame)
    EVT_DIRPICKER_CHANGED(DirPickerID,   Picker::OnPathChanged)
	EVT_FILEPICKER_CHANGED(FilePickerID, Picker::OnPathChanged)
wxEND_EVENT_TABLE()

//********************************************************
Picker::Picker(const wxString& title)
    : wxFrame(NULL, wxID_ANY, title), m_textCtrl(0)
{
    // Create a top-level panel to hold all the contents of the frame
    wxPanel* panel1 = new wxPanel(this, wxID_ANY);
    wxPanel* panel2 = new wxPanel(this, wxID_ANY);

    // Create a wxFilePickerCtrl control
    wxDirPickerCtrl* dirPickerCtrl = new wxDirPickerCtrl(panel1, DirPickerID,
        wxEmptyString, wxDirSelectorPromptStr,
        wxDefaultPosition, wxSize(350, wxDefaultCoord));

    // Create a wxFilePickerCtrl control
    wxFilePickerCtrl* filePickerCtrl = new wxFilePickerCtrl(panel2, FilePickerID,
        wxEmptyString, wxDirSelectorPromptStr, wxFileSelectorDefaultWildcardStr,
        wxDefaultPosition, wxSize(350, wxDefaultCoord));

    // We add a wxTextCtrl that will contain the same path as
    // the wxDirPickerCtrl. This is done by using the event
    // generated by the wxDirPickerCtrl when the path changes.
    wxStaticText* staticText1 = new wxStaticText(panel1, wxID_ANY, "Selected Path:");
    m_textCtrl = new wxTextCtrl(panel1, wxID_ANY);

//    wxStaticText* staticText2 = new wxStaticText(panel2, wxID_ANY, "Selected File:");
//    m_textCtrl2 = new wxTextCtrl(panel2, wxID_ANY);

    // Set up the sizer for the panel1
    wxBoxSizer* panelSizer = new wxBoxSizer(wxVERTICAL);
    panelSizer->Add(dirPickerCtrl, 0, wxEXPAND | wxALL, 5);
    panelSizer->AddSpacer(15);
    panelSizer->Add(staticText1, 0, wxEXPAND | wxLEFT, 5);
    panelSizer->Add(m_textCtrl, 0, wxEXPAND | wxALL, 5);
    panel1->SetSizer(panelSizer);
  // Set up the sizer for the panel2
    wxBoxSizer* panelSizer2 = new wxBoxSizer(wxVERTICAL);
    panelSizer2->Add(filePickerCtrl, 0, wxEXPAND | wxALL, 5);
//    panelSizer2->AddSpacer(15);
//    panelSizer2->Add(staticText2, 0, wxEXPAND | wxLEFT, 5);
//    panelSizer2->Add(m_textCtrl2, 0, wxEXPAND | wxALL, 5);
    panel2->SetSizer(panelSizer2);

    // Set up the sizer for the frame and resize the frame
    // according to its contents
    wxBoxSizer* topSizer = new wxBoxSizer(wxHORIZONTAL);
    topSizer->Add(panel1, 1, wxEXPAND);
    topSizer->Add(panel2, 1, wxEXPAND);
    SetSizerAndFit(topSizer);
}

// This event handler will be called when the path
// of the wxDirPickerCtrl has changed
void Picker::OnPathChanged(wxFileDirPickerEvent& evt) {
//	if(evt.GetId()==6001)
	    if(m_textCtrl)
	        m_textCtrl->SetValue(evt.GetPath());
//	if(evt.GetId()==6000)
//	    if(m_textCtrl2)
//	      m_textCtrl2->SetValue(evt.GetPath());
        //m_textCtrl->SetValue(evt.GetClassInfo()->GetClassName());
}